### ISSUE TITLE
no docker-compose.yml?!

### ISSUE THREAD

**Issue by iNoSec2** [Dynamictivity/cakephp-bookmarker#1]
hello,
you dont have any docker-compose.yml you talked about in the readme...

**Comment by Theaxiom** [comment]
It is a part of this project: https://github.com/Dynamictivity/docker-cakephp-cloud

**Comment by Theaxiom** [comment]
Or this project: https://github.com/Dynamictivity/docker-cakephp

It is a multi-project build. This example utilizes the `docker-cakephp` framework and shows an example as to how to utilize it.
